---
title: "Running EcoAssocNet from R"
output: html_notebook
---

```{r setup}
knitr::opts_knit$set(root.dir = 'D:/Data-driven/MTEC/EcoAssocNet/Source code')
```

### Configuration
First, configure RStudio to use the virtual environments where you installed GeoAssocNet and its dependencies. 

```{r, warning=FALSE}
library(reticulate)
use_condaenv("phd")
py_config()
```

### Importing geoassocnet
```{r, warning=FALSE, echo=FALSE}
source_python("run_geoassoc.py")
```

### Loading and preprocessing data
```{r, warning=FALSE}
training_output=run_geoassoc(folder_data="examples/Aravo/data/",file_env="env.csv",file_count="occur.csv",
                 training_config_file="examples/Aravo/config/association_learning.ini",
                 name_dataset="aravo",target="count",
                 num_vars=c("Slope","PhysD","Snow"),cat_vars=c("Aspect","Form","ZoogD"),
                num_std="minmax",cat_trt="onehot",
                 offset_mode="avgnz",verbose=0,
                 meth="stratified",p=0.8)

model=training_output$model
data=training_output$data
metadata=training_output$metadata
```

### Retrieving and filtering associations
```{r}
assoc_mat=model$compute_associations(save=FALSE,norm=TRUE)

selected_assoc_mat=apply_biogeo_filter(assoc_df=assoc_mat,occur=data$occur,weights=model$mle$final_weights,thoccur=0,thass=0.75,thresp=0.5,names=metadata$names)
```

### Visualization
```{r}
util <-import("ecoassocnet.Util.Util")
### Loading the final association matrix 
assoc <- read.csv2('examples/Aravo/results/plant_associations.csv',row.names = 1)
util$plot_association(mat=assoc,fileout='examples/Aravo/results/assoc.pdf')
util$plot_assoc_clustered(assoc,file='examples/Aravo/results/assoc_clustered.pdf')
```

